---
# Setup automatic updates for RHEL-based machines.

- name: Setup automatic updates for RHEL-based operating system
  when:
    - auto_updates | bool
    - ansible_facts["os_family"] == "RedHat"
  block:
    - name: Copy notification scheduler script to /usr/local/bin/
      ansible.builtin.copy:
        src: files/scripts/notify-update
        dest: /usr/local/bin/notify-update
        mode: "0755"

    - name: Copy notification sender script to /usr/local/bin/
      ansible.builtin.copy:
        src: files/scripts/notify-update-send
        dest: /usr/local/bin/notify-update-send
        mode: "0755"

    - name: Configure dnf-automatic
      ansible.builtin.template:
        src: files/configs/dnf_automatic.conf
        dest: /etc/dnf/automatic.conf
        mode: "0644"

    - name: Create systemd drop-in directory for dnf-automatic.service
      ansible.builtin.file:
        path: /usr/lib/systemd/system/dnf-automatic.service.d
        state: directory
        mode: "0755"

    - name: Add environment variable to dnf-automatic systemd service
      ansible.builtin.copy:
        dest: /usr/lib/systemd/system/dnf-automatic.service.d/env.conf
        mode: "0644"
        content: |
          [Service]
          Environment="AUTOMATIC_REBOOT_TIME={{ automatic_reboot_time }}"
          Environment="DISCORD_WEBHOOK={{ vault_discord_webhook }}"

    - name: Create dnf-automatic.service.d directory
      ansible.builtin.file:
        path: /etc/systemd/system/dnf-automatic.timer.d/
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Deploy dnf-automatic.timer override (change timer to run at 08:00)
      ansible.builtin.template:
        src: files/configs/dnf_automatic_override.conf
        dest: /etc/systemd/system/dnf-automatic.timer.d/override.conf
        mode: "0644"

    - name: Reload systemd to pick up the changes
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Ensure dnf-automatic timer is enabled
      ansible.builtin.systemd:
        name: dnf-automatic.timer
        enabled: true
        state: started

# Setup automatic updates for Debian-based machines.

- name: Setup automatic updates for Debian-based operating system
  ansible.builtin.debug:
    msg: Not yet implemented!
  when:
    - auto_updates | bool
    - ansible_facts["os_family"] == "Debian"
