---
- name: Set hostname from inventory
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Configure VM MOTD
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
